networks:
  favorite-places:

services:
  # GraphQL API Gateway
  favorite-places-gateway:
    build: ./graphql
    container_name: favorite-places-gateway
    command: flask --debug run --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - ./graphql/src:/src
      - ./graphql/docs:/docs
    env_file:
      - graphql/.env
    networks:
      - favorite-places
